Web_Store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('', include('shop.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

shop/urls.py
from django.urls import path

from .views import item_details, store, tag_details, tag_list

app_name = 'store'


urlpatterns = [
    path('', store, name='home'),
    path('categories/', tag_list, name='tag_list'),
    path('category-details/<slug:slug>/', tag_details, name='tag_details'),
    path('<slug:item_slug>/', item_details, name='item_details'),
]

templates/store/item_details.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h2>{{ item.title }}</h2>
<p>Товар принадлежит к категории
{% for tag in item.tags.all %}
    <b><a href="{% url 'store:tag_details' tag.slug %}">{{ tag }}</a></b>
    {% if not forloop.last %},{% endif %}
{% endfor %}
</p>
{% if item.image %}
    <p><span class="image left"><img src="{{ item.image.url }}" alt="" style="max-width: 200px; max-height: 200px;"/>
{% else %}
    <p><span class="image left"><img src="{% static "images/pic14.jpg" %}" alt="" />
{% endif %}
    <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:10px;">
        Добавить в корзину</a>
    </span>
    {{ item.description }}{{ item.description }}
</p>
{% if item.old_price %}
    <p>Старая цена: <s>{{ item.old_price }} рублей</s>
    Новая цена: <b>{{ item.price }}</b> рублей </p>
{% else %}
    <p>Цена: <b>{{ item.price }}</b> рублей </p>
{% endif %}
{% endblock %} 

templates/store/main_page.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h1>APPLE AGENT<br /></h1>
<p>Это современный магазин и сервис техники Apple в Минске. Мы релиазиуем исключительно оригинальную технику Apple. </p>
<p>Гарантия 12 месяцев. Доставка по Минску 0 BYN</p>    
<section class="tiles">
    {% for item in page_obj %}
    <article class="style{{ range|random }}">
        <span class="image">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt="" style="width: 200px; height: 200px;" />
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        </span>
        <a href="{% url 'store:item_details' item.slug %}">
            <div class="tag">
                <object> 
                    {% for tag in item.tags.all %}
                        <a href="{% url 'store:tag_details' tag.slug %}" style="color: black">{{ tag }}</a>
                        {% if not forloop.last %},{% endif %}
                    {% endfor %}
                </object><br />
            </div>
            <h2>{{ item.title }}</h2>
            <div class="content">
                <p>{{ item.description|truncatechars:150 }}</p>
            </div>
        </a>
    </article>
    {% endfor %}
</section>
{% endblock %} 

templates/store/tag_details.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>{{ tag.name }}</h2>
    Количество товаров:&ensp;{{ tag.items.count }}
    <p><a href="{% url 'store:tag_list'%}"><b>Все категории</b></a></p>
    <hr>
{% for item in page_obj %}
    <a href="{% url 'store:item_details' item.slug %}"><b>{{ item.title }}</b></a>
    <p><span class="image left">
        {% if item.image %}
            <img src="{{ item.image.url }}" alt="" style="max-width: 150px; max-height: 150px;"/>
        {% else %}
            <img src="{% static "images/pic01.jpg" %}" alt="" />
        {% endif %}
        <a href="{% url 'cart:add_to_cart' item.slug %}" class="button small" style="margin-top:15px;">
            Добавить в корзину</a>
        </span>
    </p>
    <p>{{ item.description }}</p>
    {% if item.old_price %}
        <p>Старая цена: <s>{{ item.old_price }} рублей</s>
        Новая цена: <b>{{ item.price }}</b> рублей </p>
    {% else %}
        <p>Цена: <b>{{ item.price }}</b> рублей </p>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %} 

templates/store/tag_list.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <h2>Выбор категории</h2>
    <hr>
{% for tag in page_obj %}
    <a href="{% url 'store:tag_details' tag.slug %}"><b>{{ tag.name }}</b></a>
    <p><span class="image right">
        {% if tag.image %}
            <img src="{{ tag.image.url }}" alt="" style="width: 100px; height: 100px;"/>
        {% else %}
            <img src="{% static "images/pic14.jpg" %}" alt="" />
        {% endif %}
    </span>{{tag.description}}{{tag.description}}</p>
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %} 